import type {
  DirectionHypothesis,
  EvidencePackage,
  OpportunityThesis,
} from "../../domain/contracts";
import {
  OPPORTUNITY_FAMILIES,
  type OpportunityFamily,
  type OpportunityPattern,
} from "../../domain/product-constitution";

export const M3_FAMILY_ANALYSIS_POLICY_VERSION =
  "m3-family-analysis-policy.v1-uncalibrated" as const;

export const M3_FAMILY_ANALYSIS_CATEGORIES = [
  "STRUCTURE",
  "LOCATION",
  "SPACE",
  "PARTICIPATION",
  "LIQUIDITY",
  "DERIVATIVES",
  "CROSS_VENUE",
  "BENCHMARK_RELATIVE",
  "TIMING",
  "MARKET_CONTEXT",
  "NOISE",
] as const;

export type M3FamilyAnalysisCategory =
  (typeof M3_FAMILY_ANALYSIS_CATEGORIES)[number];
type EvidenceStance = EvidencePackage["items"][number]["stance"];

export const M3_FAMILY_ANALYSIS_OBSERVATION_CODES = [
  "PRE_MOVE_COMPRESSION_PRESENT",
  "PRE_MOVE_FLOW_LEADS_LONG",
  "PRE_MOVE_FLOW_LEADS_SHORT",
  "PRE_MOVE_LIQUIDITY_TRANSITION",
  "PRE_MOVE_MOVE_CONSUMED",
  "PRE_MOVE_THIN_SINGLE_VENUE",
  "BREAKOUT_BOUNDARY_LONG",
  "BREAKOUT_BOUNDARY_SHORT",
  "BREAKOUT_ROLE_FLIP_LONG",
  "BREAKOUT_ROLE_FLIP_SHORT",
  "BREAKOUT_PARTICIPATION_CONFIRMED",
  "BREAKOUT_RETEST_PENDING",
  "BREAKOUT_RETURNED_INSIDE",
  "BREAKOUT_SPACE_CONSTRAINED",
  "TREND_UP_STRUCTURE_INTACT",
  "TREND_DOWN_STRUCTURE_INTACT",
  "TREND_PULLBACK_LONG_HOLDS",
  "TREND_PULLBACK_SHORT_HOLDS",
  "TREND_MOMENTUM_RESUMES",
  "TREND_STRUCTURE_DAMAGED",
  "TREND_EXTENSION_CONSUMED",
  "REVERSAL_SUPPORT_SWEEP_RECLAIMED",
  "REVERSAL_RESISTANCE_SWEEP_REJECTED",
  "REVERSAL_RANGE_LOW_REACTION",
  "REVERSAL_RANGE_HIGH_REACTION",
  "REVERSAL_CONFIRMATION_PENDING",
  "REVERSAL_SWEEP_NOT_RECLAIMED",
  "REVERSAL_RANGE_EXPANDS_AGAINST",
  "RELATIVE_BENCHMARK_STRENGTH",
  "RELATIVE_BENCHMARK_WEAKNESS",
  "RELATIVE_PEER_PERSISTENCE",
  "RELATIVE_LOW_TURNOVER_DISTORTION",
  "RELATIVE_BENCHMARK_SHOCK",
  "RELATIVE_NOT_PERSISTENT",
  "DERIVATIVES_BULLISH_PRICE_OI_DIVERGENCE",
  "DERIVATIVES_BEARISH_PRICE_OI_DIVERGENCE",
  "DERIVATIVES_BULLISH_CROWDING_RELEASE",
  "DERIVATIVES_BEARISH_CROWDING_RELEASE",
  "DERIVATIVES_BULLISH_FUNDING_BASIS_DISLOCATION",
  "DERIVATIVES_BEARISH_FUNDING_BASIS_DISLOCATION",
  "DERIVATIVES_POSITIONING_OVERHEATED",
  "DERIVATIVES_POST_LIQUIDATION_NOISE",
  "DERIVATIVES_CAPABILITY_MISSING",
  "STRUCTURE_CONTEXT_CONFIRMED",
  "LOCATION_STRUCTURAL_GOOD",
  "LOCATION_STRUCTURAL_ACCEPTABLE",
  "LOCATION_EXTENDED_OR_CHASE",
  "SPACE_STRUCTURAL_GOOD",
  "SPACE_STRUCTURAL_ACCEPTABLE",
  "SPACE_CONSTRAINED",
  "PARTICIPATION_CONFIRMED",
  "TIMING_EARLY_OR_NOT_CONSUMED",
  "CROSS_VENUE_CONFIRMED",
  "CROSS_VENUE_CONFLICT",
  "NOISE_ELEVATED",
] as const;

export type M3FamilyAnalysisObservationCode =
  (typeof M3_FAMILY_ANALYSIS_OBSERVATION_CODES)[number];

type ObservationDefinition = Readonly<{
  families: readonly OpportunityFamily[];
  category: M3FamilyAnalysisCategory;
  stance: EvidenceStance;
  direction: DirectionHypothesis;
}>;

function definition(
  families: readonly OpportunityFamily[],
  category: M3FamilyAnalysisCategory,
  stance: EvidenceStance,
  direction: DirectionHypothesis = "UNKNOWN",
): ObservationDefinition {
  return { families, category, stance, direction };
}

export const M3_FAMILY_ANALYSIS_OBSERVATION_DEFINITIONS = Object.freeze({
  PRE_MOVE_COMPRESSION_PRESENT: definition(["PRE_MOVE"], "STRUCTURE", "SUPPORTING"),
  PRE_MOVE_FLOW_LEADS_LONG: definition(["PRE_MOVE"], "PARTICIPATION", "SUPPORTING", "LONG"),
  PRE_MOVE_FLOW_LEADS_SHORT: definition(["PRE_MOVE"], "PARTICIPATION", "SUPPORTING", "SHORT"),
  PRE_MOVE_LIQUIDITY_TRANSITION: definition(["PRE_MOVE"], "LIQUIDITY", "SUPPORTING"),
  PRE_MOVE_MOVE_CONSUMED: definition(["PRE_MOVE"], "TIMING", "CONTRADICTING"),
  PRE_MOVE_THIN_SINGLE_VENUE: definition(["PRE_MOVE"], "NOISE", "CONTRADICTING"),
  BREAKOUT_BOUNDARY_LONG: definition(["BREAKOUT_RETEST"], "STRUCTURE", "SUPPORTING", "LONG"),
  BREAKOUT_BOUNDARY_SHORT: definition(["BREAKOUT_RETEST"], "STRUCTURE", "SUPPORTING", "SHORT"),
  BREAKOUT_ROLE_FLIP_LONG: definition(["BREAKOUT_RETEST"], "STRUCTURE", "SUPPORTING", "LONG"),
  BREAKOUT_ROLE_FLIP_SHORT: definition(["BREAKOUT_RETEST"], "STRUCTURE", "SUPPORTING", "SHORT"),
  BREAKOUT_PARTICIPATION_CONFIRMED: definition(["BREAKOUT_RETEST"], "PARTICIPATION", "SUPPORTING"),
  BREAKOUT_RETEST_PENDING: definition(["BREAKOUT_RETEST"], "TIMING", "MISSING"),
  BREAKOUT_RETURNED_INSIDE: definition(["BREAKOUT_RETEST"], "STRUCTURE", "CONTRADICTING"),
  BREAKOUT_SPACE_CONSTRAINED: definition(["BREAKOUT_RETEST"], "LOCATION", "CONTRADICTING"),
  TREND_UP_STRUCTURE_INTACT: definition(["TREND_CONTINUATION"], "STRUCTURE", "SUPPORTING", "LONG"),
  TREND_DOWN_STRUCTURE_INTACT: definition(["TREND_CONTINUATION"], "STRUCTURE", "SUPPORTING", "SHORT"),
  TREND_PULLBACK_LONG_HOLDS: definition(["TREND_CONTINUATION"], "LOCATION", "SUPPORTING", "LONG"),
  TREND_PULLBACK_SHORT_HOLDS: definition(["TREND_CONTINUATION"], "LOCATION", "SUPPORTING", "SHORT"),
  TREND_MOMENTUM_RESUMES: definition(["TREND_CONTINUATION"], "PARTICIPATION", "SUPPORTING"),
  TREND_STRUCTURE_DAMAGED: definition(["TREND_CONTINUATION"], "STRUCTURE", "CONTRADICTING"),
  TREND_EXTENSION_CONSUMED: definition(["TREND_CONTINUATION"], "TIMING", "CONTRADICTING"),
  REVERSAL_SUPPORT_SWEEP_RECLAIMED: definition(["REVERSAL_RANGE"], "STRUCTURE", "SUPPORTING", "LONG"),
  REVERSAL_RESISTANCE_SWEEP_REJECTED: definition(["REVERSAL_RANGE"], "STRUCTURE", "SUPPORTING", "SHORT"),
  REVERSAL_RANGE_LOW_REACTION: definition(["REVERSAL_RANGE"], "LOCATION", "SUPPORTING", "LONG"),
  REVERSAL_RANGE_HIGH_REACTION: definition(["REVERSAL_RANGE"], "LOCATION", "SUPPORTING", "SHORT"),
  REVERSAL_CONFIRMATION_PENDING: definition(["REVERSAL_RANGE"], "TIMING", "MISSING"),
  REVERSAL_SWEEP_NOT_RECLAIMED: definition(["REVERSAL_RANGE"], "STRUCTURE", "CONTRADICTING"),
  REVERSAL_RANGE_EXPANDS_AGAINST: definition(["REVERSAL_RANGE"], "STRUCTURE", "CONTRADICTING"),
  RELATIVE_BENCHMARK_STRENGTH: definition(["RELATIVE_STRENGTH"], "BENCHMARK_RELATIVE", "SUPPORTING", "LONG"),
  RELATIVE_BENCHMARK_WEAKNESS: definition(["RELATIVE_STRENGTH"], "BENCHMARK_RELATIVE", "SUPPORTING", "SHORT"),
  RELATIVE_PEER_PERSISTENCE: definition(["RELATIVE_STRENGTH"], "TIMING", "SUPPORTING"),
  RELATIVE_LOW_TURNOVER_DISTORTION: definition(["RELATIVE_STRENGTH"], "LIQUIDITY", "CONTRADICTING"),
  RELATIVE_BENCHMARK_SHOCK: definition(["RELATIVE_STRENGTH"], "MARKET_CONTEXT", "CONTRADICTING"),
  RELATIVE_NOT_PERSISTENT: definition(["RELATIVE_STRENGTH"], "TIMING", "CONTRADICTING"),
  DERIVATIVES_BULLISH_PRICE_OI_DIVERGENCE: definition(["DERIVATIVES_FLOW"], "DERIVATIVES", "SUPPORTING", "LONG"),
  DERIVATIVES_BEARISH_PRICE_OI_DIVERGENCE: definition(["DERIVATIVES_FLOW"], "DERIVATIVES", "SUPPORTING", "SHORT"),
  DERIVATIVES_BULLISH_CROWDING_RELEASE: definition(["DERIVATIVES_FLOW"], "DERIVATIVES", "SUPPORTING", "LONG"),
  DERIVATIVES_BEARISH_CROWDING_RELEASE: definition(["DERIVATIVES_FLOW"], "DERIVATIVES", "SUPPORTING", "SHORT"),
  DERIVATIVES_BULLISH_FUNDING_BASIS_DISLOCATION: definition(["DERIVATIVES_FLOW"], "DERIVATIVES", "SUPPORTING", "LONG"),
  DERIVATIVES_BEARISH_FUNDING_BASIS_DISLOCATION: definition(["DERIVATIVES_FLOW"], "DERIVATIVES", "SUPPORTING", "SHORT"),
  DERIVATIVES_POSITIONING_OVERHEATED: definition(["DERIVATIVES_FLOW"], "DERIVATIVES", "CONTRADICTING"),
  DERIVATIVES_POST_LIQUIDATION_NOISE: definition(["DERIVATIVES_FLOW"], "NOISE", "CONTRADICTING"),
  DERIVATIVES_CAPABILITY_MISSING: definition(["DERIVATIVES_FLOW"], "DERIVATIVES", "MISSING"),
  STRUCTURE_CONTEXT_CONFIRMED: definition(OPPORTUNITY_FAMILIES, "STRUCTURE", "SUPPORTING"),
  LOCATION_STRUCTURAL_GOOD: definition(OPPORTUNITY_FAMILIES, "LOCATION", "SUPPORTING"),
  LOCATION_STRUCTURAL_ACCEPTABLE: definition(OPPORTUNITY_FAMILIES, "LOCATION", "SUPPORTING"),
  LOCATION_EXTENDED_OR_CHASE: definition(OPPORTUNITY_FAMILIES, "LOCATION", "CONTRADICTING"),
  SPACE_STRUCTURAL_GOOD: definition(OPPORTUNITY_FAMILIES, "SPACE", "SUPPORTING"),
  SPACE_STRUCTURAL_ACCEPTABLE: definition(OPPORTUNITY_FAMILIES, "SPACE", "SUPPORTING"),
  SPACE_CONSTRAINED: definition(OPPORTUNITY_FAMILIES, "SPACE", "CONTRADICTING"),
  PARTICIPATION_CONFIRMED: definition(OPPORTUNITY_FAMILIES, "PARTICIPATION", "SUPPORTING"),
  TIMING_EARLY_OR_NOT_CONSUMED: definition(OPPORTUNITY_FAMILIES, "TIMING", "SUPPORTING"),
  CROSS_VENUE_CONFIRMED: definition(OPPORTUNITY_FAMILIES, "CROSS_VENUE", "SUPPORTING"),
  CROSS_VENUE_CONFLICT: definition(OPPORTUNITY_FAMILIES, "CROSS_VENUE", "CONTRADICTING"),
  NOISE_ELEVATED: definition(OPPORTUNITY_FAMILIES, "NOISE", "CONTRADICTING"),
} satisfies Record<M3FamilyAnalysisObservationCode, ObservationDefinition>);

const REQUIRED_CATEGORIES_BY_PATTERN = Object.freeze({
  PRE_MOVE_COMPRESSION: ["STRUCTURE", "PARTICIPATION", "SPACE", "TIMING"],
  PRE_MOVE_FLOW_DIVERGENCE: ["STRUCTURE", "PARTICIPATION", "SPACE", "TIMING"],
  PRE_MOVE_LIQUIDITY_SHIFT: ["LIQUIDITY", "CROSS_VENUE", "SPACE", "TIMING"],
  BREAKOUT_EDGE: ["STRUCTURE", "PARTICIPATION", "LOCATION", "SPACE"],
  ROLE_FLIP_RETEST: ["STRUCTURE", "PARTICIPATION", "LOCATION", "SPACE"],
  TREND_COMPRESSION: ["STRUCTURE", "PARTICIPATION", "SPACE", "TIMING"],
  STRUCTURAL_PULLBACK_RESUMPTION: ["STRUCTURE", "PARTICIPATION", "LOCATION", "SPACE"],
  KEY_LEVEL_REVERSAL: ["STRUCTURE", "PARTICIPATION", "LOCATION", "SPACE"],
  RANGE_EDGE: ["STRUCTURE", "PARTICIPATION", "LOCATION", "SPACE"],
  RELATIVE_STRENGTH: ["BENCHMARK_RELATIVE", "PARTICIPATION", "SPACE", "TIMING"],
  RELATIVE_WEAKNESS: ["BENCHMARK_RELATIVE", "PARTICIPATION", "SPACE", "TIMING"],
  PRICE_OI_DIVERGENCE: ["DERIVATIVES", "STRUCTURE", "SPACE", "TIMING"],
  CROWDING_RELEASE: ["DERIVATIVES", "PARTICIPATION", "SPACE", "TIMING"],
  FUNDING_BASIS_DISLOCATION: ["DERIVATIVES", "CROSS_VENUE", "SPACE", "TIMING"],
} as const satisfies Record<OpportunityPattern, readonly M3FamilyAnalysisCategory[]>);

export function requiredM3FamilyAnalysisCategories(
  thesis: OpportunityThesis,
): M3FamilyAnalysisCategory[] {
  return [...new Set(thesis.opportunityPatterns.flatMap((pattern) =>
    REQUIRED_CATEGORIES_BY_PATTERN[pattern]
  ))].sort() as M3FamilyAnalysisCategory[];
}

export type M3FamilyAnalysisResolution = Readonly<{
  structureState: string;
  marketStage: string;
}>;

function unresolved(): M3FamilyAnalysisResolution {
  return { structureState: "UNRESOLVED", marketStage: "UNKNOWN" };
}

export function resolveM3FamilyAnalysis(
  family: OpportunityFamily,
  found: ReadonlySet<M3FamilyAnalysisObservationCode>,
): M3FamilyAnalysisResolution {
  if (family === "PRE_MOVE") {
    if (found.has("PRE_MOVE_MOVE_CONSUMED")) return { structureState: "EARLY_STRUCTURE_INVALIDATED", marketStage: "LATE_OR_CONSUMED" };
    if (found.has("PRE_MOVE_THIN_SINGLE_VENUE")) return { structureState: "THIN_LIQUIDITY_DISTORTION", marketStage: "UNRESOLVED" };
    if (found.has("PRE_MOVE_COMPRESSION_PRESENT")) return { structureState: "COMPRESSION_WITH_DIRECTIONAL_PRESSURE", marketStage: "EARLY" };
    if (found.has("PRE_MOVE_LIQUIDITY_TRANSITION")) return { structureState: "LIQUIDITY_STATE_TRANSITION", marketStage: "EARLY_UNCONFIRMED" };
    return unresolved();
  }
  if (family === "BREAKOUT_RETEST") {
    if (found.has("BREAKOUT_RETURNED_INSIDE")) return { structureState: "BREAKOUT_FAILED_RETURNED_INSIDE", marketStage: "INVALIDATED" };
    if (found.has("BREAKOUT_ROLE_FLIP_LONG") || found.has("BREAKOUT_ROLE_FLIP_SHORT")) return { structureState: "ROLE_FLIP_RETEST_HOLD", marketStage: "RETEST" };
    if (found.has("BREAKOUT_BOUNDARY_LONG") || found.has("BREAKOUT_BOUNDARY_SHORT")) return { structureState: "BOUNDARY_BREAK_ACCEPTANCE", marketStage: "BREAKOUT" };
    if (found.has("BREAKOUT_RETEST_PENDING")) return { structureState: "BOUNDARY_BREAK_UNCONFIRMED", marketStage: "RETEST_PENDING" };
    return unresolved();
  }
  if (family === "TREND_CONTINUATION") {
    if (found.has("TREND_STRUCTURE_DAMAGED")) return { structureState: "TREND_STRUCTURE_DAMAGED", marketStage: "INVALIDATED" };
    if (found.has("TREND_EXTENSION_CONSUMED")) return { structureState: "TREND_INTACT_ENTRY_LATE", marketStage: "EXTENDED" };
    if (found.has("TREND_PULLBACK_LONG_HOLDS") || found.has("TREND_PULLBACK_SHORT_HOLDS")) return { structureState: "STRUCTURAL_PULLBACK_HOLD", marketStage: "RESUMPTION" };
    if (found.has("TREND_UP_STRUCTURE_INTACT") || found.has("TREND_DOWN_STRUCTURE_INTACT")) return { structureState: "TREND_STRUCTURE_INTACT", marketStage: "PULLBACK_OR_COMPRESSION" };
    return unresolved();
  }
  if (family === "REVERSAL_RANGE") {
    if (found.has("REVERSAL_SWEEP_NOT_RECLAIMED") || found.has("REVERSAL_RANGE_EXPANDS_AGAINST")) return { structureState: "REVERSAL_HYPOTHESIS_INVALIDATED", marketStage: "INVALIDATED" };
    if (found.has("REVERSAL_SUPPORT_SWEEP_RECLAIMED") || found.has("REVERSAL_RESISTANCE_SWEEP_REJECTED")) return { structureState: "LIQUIDITY_SWEEP_RECLAIM_OR_REJECTION", marketStage: "EARLY_REVERSAL" };
    if (found.has("REVERSAL_RANGE_LOW_REACTION") || found.has("REVERSAL_RANGE_HIGH_REACTION")) return { structureState: "RANGE_EDGE_REACTION", marketStage: "CONFIRMATION_PENDING" };
    return unresolved();
  }
  if (family === "RELATIVE_STRENGTH") {
    if (found.has("RELATIVE_NOT_PERSISTENT")) return { structureState: "RELATIVE_EDGE_DECAYED", marketStage: "INVALIDATED" };
    if (found.has("RELATIVE_LOW_TURNOVER_DISTORTION") || found.has("RELATIVE_BENCHMARK_SHOCK")) return { structureState: "RELATIVE_EDGE_DISTORTED", marketStage: "UNRESOLVED" };
    if (found.has("RELATIVE_BENCHMARK_STRENGTH") || found.has("RELATIVE_BENCHMARK_WEAKNESS")) {
      return { structureState: "BENCHMARK_ADJUSTED_DIVERGENCE", marketStage: found.has("RELATIVE_PEER_PERSISTENCE") ? "PERSISTING" : "EMERGING" };
    }
    return unresolved();
  }
  if (found.has("DERIVATIVES_CAPABILITY_MISSING")) return { structureState: "DERIVATIVES_EVIDENCE_UNAVAILABLE", marketStage: "UNKNOWN" };
  if (found.has("DERIVATIVES_POST_LIQUIDATION_NOISE")) return { structureState: "POST_LIQUIDATION_NOISE", marketStage: "POST_EVENT" };
  if (found.has("DERIVATIVES_POSITIONING_OVERHEATED")) return { structureState: "POSITIONING_OVERHEATED", marketStage: "LATE_OR_CROWDED" };
  if (found.has("DERIVATIVES_BULLISH_PRICE_OI_DIVERGENCE") || found.has("DERIVATIVES_BEARISH_PRICE_OI_DIVERGENCE")) return { structureState: "PRICE_POSITIONING_DIVERGENCE", marketStage: "EARLY_DIVERGENCE" };
  if (found.has("DERIVATIVES_BULLISH_CROWDING_RELEASE") || found.has("DERIVATIVES_BEARISH_CROWDING_RELEASE")) return { structureState: "CROWDING_RELEASE", marketStage: "REPRICING" };
  if (found.has("DERIVATIVES_BULLISH_FUNDING_BASIS_DISLOCATION") || found.has("DERIVATIVES_BEARISH_FUNDING_BASIS_DISLOCATION")) return { structureState: "FUNDING_BASIS_DISLOCATION", marketStage: "DISLOCATION" };
  return unresolved();
}

export const M3_FAMILY_ANALYSIS_HARD_INVALIDATION_CODES = Object.freeze(
  new Set<M3FamilyAnalysisObservationCode>([
    "PRE_MOVE_MOVE_CONSUMED",
    "BREAKOUT_RETURNED_INSIDE",
    "TREND_STRUCTURE_DAMAGED",
    "REVERSAL_SWEEP_NOT_RECLAIMED",
    "REVERSAL_RANGE_EXPANDS_AGAINST",
    "RELATIVE_NOT_PERSISTENT",
    "DERIVATIVES_CAPABILITY_MISSING",
  ]),
);

export function m3FamilyAnalyzerVersion(family: OpportunityFamily): string {
  return `m3-${family.toLowerCase().replaceAll("_", "-")}-family-analyzer.v1-uncalibrated`;
}
