export const STANDING_AUTHORIZATION_SCHEMA = "market-radar-g0-g8-standing-authorization.v1";
export const AUTONOMOUS_SCOPE_GATES = ["G0", "G1", "G2", "G3", "G4", "G5", "G6", "G7", "G8"];
export const PACKAGE_APPROVAL_MAX_MINUTES = 90;

export const MANDATORY_BASELINE_GATES = [
  "typecheck",
  "lint",
  "test:market",
  "build",
  "backtest:golden",
];

export const MANDATORY_SECURITY_GATES = [
  "ci:forbidden-files",
  "ci:secret-patterns",
  "security:check",
];

export const ALLOWED_ACTION_CLASSES = [
  "read_only_production_preflight",
  "reversible_service_release",
  "dormant_runtime_deploy",
  "runtime_identity_provision",
  "additive_schema_migration",
  "feature_phase_activation",
  "shadow_capture_activation",
  "shadow_verify_activation",
  "deterministic_backfill",
  "canonical_compat_activation",
  "canonical_read_cutover",
  "https_session_release",
  "release_identity_release",
  "known_incident_guard_release",
  "slo_observability_release",
  "backup_retention_configuration",
  "security_hardening_release",
  "isolated_restore_drill",
  "e2e_accessibility_load_gate_release",
  "market_fact_data_plane_release",
  "data_source_identity_release",
  "deep_scan_sla_release",
  "microstructure_feature_release",
  "candidate_episode_release",
  "relative_strength_release",
  "premove_feature_release",
  "frozen_holdout_release",
  "analysis_path_consolidation",
  "strategy_path_consolidation",
  "wait_state_release",
  "cost_model_release",
  "risk_model_release",
  "postgres_shadow_release",
  "outcome_pipeline_release",
  "frozen_ab_governance_release",
  "professional_workbench_release",
  "three_mode_review_release",
  "reminder_release",
  "paper_workflow_release",
  "readiness_evaluator_release",
  "long_horizon_governance_release",
  "degradation_monitor_release",
  "cost_decision_release",
  "exact_pollution_cleanup",
  "automatic_package_rollback",
];

export const PROHIBITED_ACTION_CLASSES = [
  "destructive_schema_change",
  "production_business_data_delete",
  "production_database_restore",
  "unknown_file_bulk_delete",
  "secret_disclosure",
  "automatic_trading",
  "exchange_order_api",
  "ready_rr_risk_gate_relaxation",
  "automatic_strategy_or_ranking_mutation",
  "future_outcome_production_input",
  "formal_backtest_auto_run",
  "unapproved_trading_rule_change",
  "observation_window_shortening",
  "gate_g9_or_later",
];

export const ACTION_RISK_TIERS = Object.freeze({
  read_only_production_preflight: "R0_READ_ONLY",
  reversible_service_release: "R1_REVERSIBLE_RUNTIME",
  dormant_runtime_deploy: "R1_REVERSIBLE_RUNTIME",
  runtime_identity_provision: "R2_PRIVILEGED_IDENTITY",
  additive_schema_migration: "R2_ADDITIVE_DATA_PLANE",
  feature_phase_activation: "R2_AUTHORITY_TRANSITION",
  shadow_capture_activation: "R2_AUTHORITY_TRANSITION",
  shadow_verify_activation: "R2_AUTHORITY_TRANSITION",
  deterministic_backfill: "R3_BOUNDED_DATA_MUTATION",
  canonical_compat_activation: "R2_AUTHORITY_TRANSITION",
  canonical_read_cutover: "R3_CANONICAL_CUTOVER",
  https_session_release: "R2_SECURITY_BOUNDARY",
  release_identity_release: "R1_REVERSIBLE_RUNTIME",
  known_incident_guard_release: "R1_REVERSIBLE_RUNTIME",
  slo_observability_release: "R1_OBSERVABILITY",
  backup_retention_configuration: "R2_RECOVERY_BOUNDARY",
  security_hardening_release: "R2_SECURITY_BOUNDARY",
  isolated_restore_drill: "R1_ISOLATED_RECOVERY",
  e2e_accessibility_load_gate_release: "R1_VERIFICATION",
  market_fact_data_plane_release: "R2_DATA_PLANE",
  data_source_identity_release: "R2_DATA_IDENTITY",
  deep_scan_sla_release: "R2_DATA_SLA",
  microstructure_feature_release: "R2_RESEARCH_FEATURE",
  candidate_episode_release: "R2_CANDIDATE_LIFECYCLE",
  relative_strength_release: "R2_CANDIDATE_RANKING",
  premove_feature_release: "R2_RESEARCH_FEATURE",
  frozen_holdout_release: "R1_FROZEN_EVALUATION",
  analysis_path_consolidation: "R2_ANALYSIS_AUTHORITY",
  strategy_path_consolidation: "R3_STRATEGY_AUTHORITY",
  wait_state_release: "R2_DECISION_SEMANTICS",
  cost_model_release: "R2_RISK_MODEL",
  risk_model_release: "R3_RISK_AUTHORITY",
  postgres_shadow_release: "R2_SHADOW_DATA_PLANE",
  outcome_pipeline_release: "R2_REVIEW_DATA_PLANE",
  frozen_ab_governance_release: "R2_RESEARCH_GOVERNANCE",
  professional_workbench_release: "R1_PRODUCT_SURFACE",
  three_mode_review_release: "R1_REVIEW_SURFACE",
  reminder_release: "R1_NOTIFICATION_SURFACE",
  paper_workflow_release: "R2_PAPER_DECISION_WORKFLOW",
  readiness_evaluator_release: "R2_READINESS_GOVERNANCE",
  long_horizon_governance_release: "R1_GOVERNANCE",
  degradation_monitor_release: "R1_OBSERVABILITY",
  cost_decision_release: "R1_COST_GOVERNANCE",
  exact_pollution_cleanup: "R1_BOUNDED_CLEANUP",
  automatic_package_rollback: "R1_APPROVED_ROLLBACK",
});

export const REQUIRED_PACKAGE_APPROVAL_FIELDS = [
  "grantId",
  "approvalId",
  "nonce",
  "gate",
  "packageId",
  "actionClass",
  "riskTier",
  "builderAgentId",
  "baseCommit",
  "targetCommit",
  "targetTree",
  "diffSha256",
  "pathSetSha256",
  "contractSha256",
  "runnerSha256",
  "artifactSha256",
  "imageOrMigrationSha256",
  "composeSha256",
  "environmentFingerprintSha256",
  "productionIdentitySha256",
  "gateEvidenceSha256",
  "preflightSha256",
  "backupRestoreEvidenceSha256",
  "rollbackTarget",
  "observationContractSha256",
  "policySha256",
  "revocationEpoch",
  "issuedAt",
  "expiresAt",
  "maxExecutions"
];
