import type {
  GoldenCaseFixture,
} from "./golden-case-types";

export const goldenCaseFixtures: GoldenCaseFixture[] = [
  {
    description: "箱体内波动收窄，OI 温和上升但没有突破，系统只能等待突破。",
    expected: {
      allowTradePlan: false,
      category: "compression",
      direction: "neutral",
      maturity: "EVIDENCE_SIGNAL",
      requiredBlockers: ["structure_confirmation_pending"],
      status: "WAIT_RETEST",
    },
    facts: {
      btcRegime: "flat",
      closePositionPct: 55,
      compressionPct: 82,
      fundingState: "neutral",
      highTimeframeConflict: false,
      oiState: "rising",
      priceAction: "compression",
      rewardRisk: 4.2,
      stopDistancePct: 2.4,
      volumeState: "normal",
      waitTriggerQuality: "none",
    },
    id: "compression-no-breakout",
    title: "压缩但未突破",
  },
  {
    description: "横盘低点抬高，回调缩量，资金温和埋伏，只能准备观察，不能抢跑。",
    expected: {
      allowTradePlan: false,
      category: "accumulation",
      direction: "long",
      maturity: "EVIDENCE_SIGNAL",
      requiredBlockers: ["structure_confirmation_pending"],
      status: "WAIT_PULLBACK",
    },
    facts: {
      btcRegime: "flat",
      closePositionPct: 45,
      compressionPct: 70,
      fundingState: "neutral",
      highTimeframeConflict: false,
      oiState: "rising",
      priceAction: "accumulating",
      rewardRisk: 3.8,
      stopDistancePct: 2.1,
      volumeState: "declining",
      waitTriggerQuality: "none",
    },
    id: "accumulation-wait-confirmation",
    title: "疑似吸筹",
  },
  {
    description: "靠近区间上沿，量能启动，资金不拥挤，仍需要突破确认。",
    expected: {
      allowTradePlan: false,
      category: "compression",
      direction: "long",
      maxRiskScore: 60,
      maturity: "EVIDENCE_SIGNAL",
      requiredBlockers: ["structure_confirmation_pending"],
      status: "WAIT_PULLBACK",
    },
    facts: {
      btcRegime: "up",
      closePositionPct: 78,
      compressionPct: 75,
      fundingState: "neutral",
      highTimeframeConflict: false,
      oiState: "rising",
      priceAction: "compression",
      rewardRisk: 3.4,
      stopDistancePct: 2.8,
      volumeState: "rising",
      waitTriggerQuality: "none",
    },
    id: "pre-breakout-edge",
    title: "突破前临界",
  },
  {
    description: "突破站稳、放量、OI 温和上升、Funding 未拥挤，RR 合格，允许计划就绪。",
    expected: {
      allowTradePlan: true,
      category: "breakout",
      direction: "long",
      maxRiskScore: 60,
      maturity: "TRADE_PLAN_READY",
      status: "READY_LONG",
    },
    facts: {
      btcRegime: "up",
      closePositionPct: 84,
      compressionPct: 45,
      fundingState: "neutral",
      highTimeframeConflict: false,
      oiState: "rising",
      priceAction: "breakout_confirmed",
      rewardRisk: 3.6,
      stopDistancePct: 2.5,
      volumeState: "spiking",
      waitTriggerQuality: "valid",
    },
    id: "quality-breakout",
    title: "优质突破",
  },
  {
    description: "价格已远离结构位，OI 暴涨，Funding 拥挤，RR 不足，只能避免追单。",
    expected: {
      allowTradePlan: false,
      category: "exhaustion",
      direction: "long",
      maturity: "REVIEW_ONLY",
      minRiskScore: 70,
      requiredBlockers: ["chase_risk", "reward_risk_below_minimum"],
      status: "BLOCKED",
    },
    facts: {
      btcRegime: "up",
      closePositionPct: 96,
      compressionPct: 15,
      fundingState: "crowded",
      highTimeframeConflict: false,
      oiState: "spiking",
      priceAction: "pumped",
      rewardRisk: 1.2,
      stopDistancePct: 8,
      volumeState: "spiking",
    },
    id: "high-risk-breakout",
    title: "高风险突破",
  },
  {
    description: "趋势完整，RSI 高位只代表动能强和追高风险，不能直接反向做空。",
    expected: {
      allowTradePlan: false,
      category: "late_move",
      direction: "long",
      maturity: "REVIEW_ONLY",
      requiredBlockers: ["chase_risk"],
      status: "WATCH_ONLY",
    },
    facts: {
      btcRegime: "up",
      closePositionPct: 90,
      compressionPct: 20,
      fundingState: "neutral",
      highTimeframeConflict: false,
      oiState: "rising",
      priceAction: "pumped",
      rewardRisk: 2.8,
      stopDistancePct: 5.5,
      volumeState: "rising",
    },
    id: "rsi-overbought-healthy-trend",
    title: "RSI 超买但趋势健康",
  },
  {
    description: "OI 暴涨但价格没有突破，Funding 偏高，属于杠杆拥挤风险。",
    expected: {
      allowTradePlan: false,
      category: "exhaustion",
      direction: "neutral",
      maturity: "EVIDENCE_SIGNAL",
      minRiskScore: 65,
      requiredBlockers: ["crowding_risk"],
      status: "WATCH_ONLY",
    },
    facts: {
      btcRegime: "flat",
      closePositionPct: 62,
      compressionPct: 40,
      fundingState: "elevated",
      highTimeframeConflict: false,
      oiState: "spiking",
      priceAction: "compression",
      rewardRisk: 2.5,
      stopDistancePct: 4,
      volumeState: "normal",
    },
    id: "oi-spike-price-stalls",
    title: "OI 暴涨但价格滞涨",
  },
  {
    description: "方向看多但目标太近、止损太远，RR 小于 3，必须拦截。",
    expected: {
      allowTradePlan: false,
      category: "rr_gate",
      direction: "long",
      maturity: "EVIDENCE_SIGNAL",
      requiredBlockers: ["reward_risk_below_minimum"],
      status: "BLOCKED",
    },
    facts: {
      btcRegime: "up",
      closePositionPct: 66,
      compressionPct: 45,
      fundingState: "neutral",
      highTimeframeConflict: false,
      oiState: "rising",
      priceAction: "pullback_reaction",
      rewardRisk: 1.8,
      stopDistancePct: 5,
      volumeState: "rising",
      waitTriggerQuality: "valid",
    },
    id: "rr-below-minimum",
    title: "盈亏比不足",
  },
  {
    description: "突破后跌回箱体，结构失效，必须移出可交易候选。",
    expected: {
      allowTradePlan: false,
      category: "fakeout",
      direction: "short",
      maturity: "REVIEW_ONLY",
      requiredBlockers: ["structure_invalidated"],
      status: "BLOCKED",
    },
    facts: {
      btcRegime: "flat",
      closePositionPct: 48,
      compressionPct: 30,
      fundingState: "neutral",
      highTimeframeConflict: false,
      oiState: "rising",
      priceAction: "breakout_failed",
      rewardRisk: 2.4,
      stopDistancePct: 4,
      volumeState: "spiking",
    },
    id: "breakout-back-into-range",
    title: "突破后跌回箱体",
  },
  {
    description: "高位创新高但能量衰减、Funding 拥挤，不能新增追多。",
    expected: {
      allowTradePlan: false,
      category: "exhaustion",
      direction: "long",
      maturity: "REVIEW_ONLY",
      minRiskScore: 70,
      requiredBlockers: ["exhaustion_risk", "chase_risk"],
      status: "WATCH_ONLY",
    },
    facts: {
      btcRegime: "up",
      closePositionPct: 95,
      compressionPct: 10,
      fundingState: "crowded",
      highTimeframeConflict: false,
      oiState: "spiking",
      priceAction: "exhaustion",
      rewardRisk: 2.2,
      stopDistancePct: 6,
      volumeState: "declining",
    },
    id: "high-level-exhaustion",
    title: "高位衰竭",
  },
  {
    description: "15m 看多，但 1h/4h 正顶关键压力，低周期不能推翻高周期。",
    expected: {
      allowTradePlan: false,
      category: "high_timeframe_conflict",
      direction: "long",
      maturity: "EVIDENCE_SIGNAL",
      requiredBlockers: ["timeframe_conflict"],
      status: "WAIT_PULLBACK",
    },
    facts: {
      btcRegime: "flat",
      closePositionPct: 80,
      compressionPct: 55,
      fundingState: "neutral",
      highTimeframeConflict: true,
      oiState: "rising",
      priceAction: "breakout_confirmed",
      rewardRisk: 3.5,
      stopDistancePct: 2.5,
      volumeState: "rising",
    },
    id: "low-tf-bull-high-tf-resistance",
    title: "小周期看多但大周期压力",
  },
  {
    description: "BTC 下跌但个币抗跌，只能加观察权重，不直接生成交易计划。",
    expected: {
      allowTradePlan: false,
      category: "accumulation",
      direction: "long",
      maturity: "EVIDENCE_SIGNAL",
      requiredBlockers: ["structure_confirmation_pending"],
      status: "WAIT_PULLBACK",
    },
    facts: {
      btcRegime: "down",
      closePositionPct: 42,
      compressionPct: 72,
      fundingState: "neutral",
      highTimeframeConflict: false,
      oiState: "flat",
      priceAction: "accumulating",
      rewardRisk: 4.1,
      stopDistancePct: 2.2,
      volumeState: "declining",
      waitTriggerQuality: "none",
    },
    id: "btc-down-alt-resilient",
    title: "BTC 下跌但山寨独立抗跌",
  },
  {
    description: "已经大涨，位置太高，哪怕方向仍强也只能风险复盘，不能追多。",
    expected: {
      allowTradePlan: false,
      category: "late_move",
      direction: "long",
      maturity: "REVIEW_ONLY",
      requiredBlockers: ["chase_risk"],
      status: "BLOCKED",
    },
    facts: {
      btcRegime: "up",
      closePositionPct: 98,
      compressionPct: 5,
      fundingState: "elevated",
      highTimeframeConflict: false,
      oiState: "rising",
      priceAction: "pumped",
      rewardRisk: 1.5,
      stopDistancePct: 7,
      volumeState: "spiking",
    },
    id: "already-pumped-no-chase",
    title: "已涨完不能追多",
  },
  {
    description: "已经大跌，短线空间变差，不能在深跌后追空。",
    expected: {
      allowTradePlan: false,
      category: "late_move",
      direction: "short",
      maturity: "REVIEW_ONLY",
      requiredBlockers: ["chase_risk"],
      status: "BLOCKED",
    },
    facts: {
      btcRegime: "down",
      closePositionPct: 3,
      compressionPct: 8,
      fundingState: "elevated",
      highTimeframeConflict: false,
      oiState: "spiking",
      priceAction: "dumped",
      rewardRisk: 1.4,
      stopDistancePct: 7.5,
      volumeState: "spiking",
    },
    id: "already-dumped-no-short-chase",
    title: "已跌深不能追空",
  },
  {
    description: "等待回踩但触发 K 线先刺破结构止损，不能算有效触发。",
    expected: {
      allowTradePlan: false,
      category: "wait_plan",
      direction: "long",
      maturity: "EVIDENCE_SIGNAL",
      requiredBlockers: ["wait_trigger_invalid"],
      status: "WAIT_PULLBACK",
    },
    facts: {
      btcRegime: "up",
      closePositionPct: 60,
      compressionPct: 45,
      fundingState: "neutral",
      highTimeframeConflict: false,
      oiState: "rising",
      priceAction: "pullback_reaction",
      rewardRisk: 3.6,
      stopDistancePct: 2.3,
      volumeState: "rising",
      waitTriggerQuality: "invalid",
    },
    id: "wait-pullback-invalid-trigger",
    title: "WAIT 回踩无效触发",
  },
  {
    description: "等待回踩触及结构位后没有刺破止损，收盘重新走强，可进入人工复核。",
    expected: {
      allowTradePlan: false,
      category: "wait_plan",
      direction: "long",
      maturity: "EVIDENCE_SIGNAL",
      requiredBlockers: ["manual_review_required"],
      status: "WAIT_PULLBACK",
    },
    facts: {
      btcRegime: "up",
      closePositionPct: 58,
      compressionPct: 45,
      fundingState: "neutral",
      highTimeframeConflict: false,
      oiState: "rising",
      priceAction: "pullback_reaction",
      rewardRisk: 3.6,
      stopDistancePct: 2.3,
      volumeState: "rising",
      waitTriggerQuality: "valid",
    },
    id: "wait-pullback-valid-trigger",
    title: "WAIT 回踩有效触发",
  },
];
